MODEL:
  INPUT_SIZE: 224
  BACKBONE: "resnet18"
  STN_MODE: "rotation_scale"
TRAIN:
  EPOCH: 50
  BATCH_SIZE: 8
  N_SHOT: 4
  N_TEST: 5
  LEARNING_RATE_STN: 1.0e-4
  LEARNING_RATE_ENC: 1.0e-4
  LEARNING_RATE_PRED: 1.0e-4
  MOMENTUM_STN: 9.0e-1
  MOMENTUM_ENC: 9.0e-1  
  MOMENTUM_PRED: 9.0e-1
  PRETRAINED: True
  DEVICE: "cpu"
  TRAIN_DATA_DIR: "/content/mvtec-ad"
  TEST_DATA_DIR: "/content/transistor"
  IGNORE_CLASS: "transistor"
  SAVE_DIR: "/content"
INFERENCE:
  CHECKPOINT_PATH: "/home/pep/Drive/PCLOUD/Projects/Anomaly-Detection/RegAD/checkpoints/screw-epoch=16-best_score=0.61.pt"
  SUPPORT_SET_PATH: "/home/pep/Drive/PCLOUD/Projects/Anomaly-Detection/RegAD/support_set/support_set.pt"